# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb9a667340da234d71a7bcb3f5e797e87166977c242b52d93e41180ac64b65f0a7101aec286574a7ccb992eb82455dbd7c413ddbf5f1c4591fd3482b0ac2ea03

test:
  secret_key_base: b372b6a243c09605f18f69513186db3c9ebbf7c5f11a1954c8589554732f2ad4628a00664604b66cda9f73ff92d212f0669b3f83ce46a4554518f9d49aa62380

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
