# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b80d28f9aa7834941c0386cda69b3bafb5d8f824dfd5460b2748582fdf68e2ef0d3485946a3c7ec6dcd3e1c98aa6cf23afb0df694e43ee7d9ad64a25511e646

test:
  secret_key_base: ce8b7b6e0e233415ebeba60629c33978bb71fa8941653e85b7f5583087068c1cae31a846c78d097a21119459d9ded0cad92dec6e471ac2ae6ce74bb1bae443ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
